// Cópia de reserva dos dados da planilha.
// Só é usada quando a apresentação abre pela primeira vez sem internet.
// Com internet, os dados vêm sempre da planilha "Apresentação Redecon – Dados".
window.DADOS_PADRAO = {
  atualizadoEm: "2026-10-02",
  parametros: {
    selic_auto: 0.1375, selic_manual: null, pct_selic_credito: 0.80,
    reajuste_aa: 0.05, incc_12m: null, lance_embutido: 0.30, meses_sem_pagar_lance: 2,
    seguro_prestamista: 0.00055, agio_venda: 0.20, venda_tir_ref: 0.01,
    cdi_auto: 0.1365, cdb_pct_cdi: 1.00, poupanca_am: 0.005, tr_aa: 0.01166,
    fin_taxa_aa: 0.115, fin_entrada: 0.20, fin_prazo: 360, fin_sistema: "SAC", fin_cet_aa: null,
    aluguel_am: 0.004, aluguel_barracao_am: 0.01, dolar_reserva: 5.22, st_diaria_usd: 40, st_ocupacao: 0.75, st_custos: 0.40,
    ex_credito: 1000000, ex_prazo: 220, ex_parcela: "meia"
  },
  indices: { selic: { data: "16/09/2026", valor: 13.75 }, cdi: { data: null, valor: 13.65 }, dolar: { data: null, valor: 5.2238 } },
  alternativas: [
    { nome: "Barracão comercial", taxa_am: 0.01, tipo: "percentual", obs: "Construção de custo mais baixo, contratos longos e pouca manutenção, que costuma ficar com a empresa inquilina." },
    { nome: "Centro de eventos", taxa_am: null, tipo: "por evento", valor_evento: null, eventos_mes: 4, obs: "Espaço alugado por evento, como formaturas, casamentos e festas, geralmente nos fins de semana." }
  ],
  cidades: [
    { cidade: "Curitiba", diaria_usd: 48, ocupacao: 0.398, fonte: "AirROI ago/25-jul/26" },
    { cidade: "Balneário Camboriú", diaria_usd: 132, ocupacao: 0.361, fonte: "AirROI ago/25-jul/26" },
    { cidade: "Itapema", diaria_usd: 129, ocupacao: 0.350, fonte: "AirROI ago/25-jul/26" },
    { cidade: "Florianópolis", diaria_usd: 119, ocupacao: 0.369, fonte: "AirROI ago/25-jul/26" },
    { cidade: "Gramado", diaria_usd: 105, ocupacao: 0.337, fonte: "AirROI ago/25-jul/26" },
    { cidade: "Foz do Iguaçu", diaria_usd: 70, ocupacao: 0.393, fonte: "AirROI ago/25-jul/26" }
  ],
  prazos: [
    { prazo: 180, taxa_adm: 0.22, fundo_reserva: 0.01 },
    { prazo: 200, taxa_adm: 0.22, fundo_reserva: 0.01 },
    { prazo: 220, taxa_adm: 0.22, fundo_reserva: 0.01 },
    { prazo: 240, taxa_adm: 0.23, fundo_reserva: 0.01 }
  ],
  funil: [
    { modalidade: "Sorteio", condicao: "Parcela em dia", meses: 0, concorrencia: 0.90, obs: "" },
    { modalidade: "Lance Limitado", condicao: "Parcela em dia", meses: 0, concorrencia: 0.85, obs: "" },
    { modalidade: "Fidelidade 1", condicao: "6 parcelas consecutivas em dia", meses: 6, concorrencia: 0.50, obs: "" },
    { modalidade: "Fidelidade 2", condicao: "12 parcelas consecutivas em dia", meses: 12, concorrencia: 0.35, obs: "" },
    { modalidade: "Fidelidade 3", condicao: "18 parcelas consecutivas em dia", meses: 18, concorrencia: 0.15, obs: "" },
    { modalidade: "Fidelidade 4", condicao: "24 parcelas consecutivas em dia", meses: 24, concorrencia: 0.07, obs: "" }
  ],
  ir: [
    { ate: 180, aliquota: 0.225 }, { ate: 360, aliquota: 0.20 },
    { ate: 720, aliquota: 0.175 }, { ate: 99999, aliquota: 0.15 }
  ],
  institucional: {
    hs_corretores: "+1.000", hs_cidades: "+1.400", hs_cotas: "+400 mil",
    hs_vendas_ano: "+R$ 27 bi", hs_vendas_mes: "+R$ 2,5 bi", hs_contemplacoes: "+2 mil",
    rd_clientes: "+3.200", rd_creditos: "+R$ 1 bi", rd_anos: "+15", rd_bens: "+900",
    ct_instagram: "@redeconconsorcios", ct_instagram_url: "https://www.instagram.com/redeconconsorcios/",
    ct_site: "www.redeconconsorcios.com.br", ct_telefone: "(46) 3025-3227"
  },
  inst_rot: {
    hs_corretores: "corretores ativos", hs_cidades: "cidades de atuação", hs_cotas: "cotas ativas",
    hs_vendas_ano: "em vendas em 2025", hs_vendas_mes: "em vendas por mês", hs_contemplacoes: "contemplações por mês",
    rd_clientes: "clientes no Brasil e em outros 12 países", rd_creditos: "em créditos comercializados",
    rd_anos: "anos de empresa, pioneira na região", rd_bens: "bens entregues"
  },
  casos: [],
  textos: {
    prop_ind_aquisicao: "A Redecon indica a meia parcela com foco nas fidelidades: você chega ao imóvel sem entrada, sem juros e sem se descapitalizar.",
    prop_ind_poupanca: "A Redecon indica a disciplina da parcela em dia: o crédito é reajustado todo ano e as fidelidades vão sendo liberadas.",
    prop_ind_investimento: "A Redecon indica contemplar e escolher o melhor caminho para o crédito: deixá-lo rendendo, vender a carta ou investir em um imóvel para renda.",
    prop_ind_comprar: "A Redecon indica a meia parcela com foco nas fidelidades: você chega ao imóvel sem entrada, sem juros e sem se descapitalizar.",
    prop_ind_quitar: "A Redecon indica trocar os juros do banco pela taxa do consórcio: contemplado, o crédito quita o saldo do financiamento.",
    prop_ind_render: "A Redecon indica contemplar e manter o crédito aplicado: o rendimento é sobre o valor total e pode ajudar a pagar a parcela.",
    prop_ind_vender: "A Redecon indica acelerar a contemplação com as fidelidades: quanto mais cedo contempla, maior a vantagem da venda da carta.",
    prop_ind_aluguel: "A Redecon indica usar o crédito em um imóvel com boa demanda de locação: o aluguel ajuda a pagar a parcela e forma patrimônio.",
    prop_ind_poupar: "A Redecon indica a disciplina da parcela em dia: o crédito é reajustado todo ano e as fidelidades vão sendo liberadas.",
    prop_titulo: "Proposta direcionada",
    prop_aviso: "Simulação estimada, com base nas premissas atuais. Os valores podem variar. A contemplação ocorre por sorteio ou lance e não é garantida; esta proposta não representa promessa de contemplação nem de rentabilidade.",
    sint_ren_frase: "Rende sobre o crédito, não sobre o que você pagou.",
    sint_ren_t: "Rendimento",
    sint_liq_frase: "Contemplou? Você decide o caminho.",
    sint_liq_t: "Liberdade de escolha",
    sint_seg_frase: "O seu capital continua seu.",
    sint_seg_t: "Segurança",
    quem_titulo: "Quem está ao seu lado nessa decisão",
    quem_cadeia_titulo: "A estrutura por trás da sua cota",
    cadeia_bc_t: "Banco Central",
    cadeia_bc: "Regula e fiscaliza o sistema de consórcios.",
    cadeia_herval_t: "Grupo Herval",
    cadeia_herval: "Grupo empresarial que controla a HS Consórcios.",
    cadeia_hs_t: "HS Consórcios",
    cadeia_hs: "Administradora dos grupos, autorizada pelo Banco Central.",
    cadeia_rd_t: "Redecon Consórcios",
    cadeia_rd: "Escritório parceiro da HS: orienta, acompanha e cuida de você do início ao fim.",
    hs_titulo: "HS Consórcios no Brasil",
    virada_titulo: "Do consórcio tradicional à inteligência financeira",
    virada_antes_t: "O consórcio do passado",
    virada_antes: "Casa, carro e moto: entrar no grupo, esperar a sorte e usar o crédito. Esse modelo ficou para trás.",
    virada_depois_t: "O consórcio de hoje",
    virada_depois: "Com a meia parcela, o consórcio vira ativo financeiro: o crédito cresce, rende e pode ser usado, vendido ou transformado em renda.",
    virada_frase: "De bem de consumo a ativo financeiro.",
    virada_usos: "Comprar, construir ou quitar um financiamento; Vender a carta contemplada; Deixar o crédito rendendo até decidir; Gerar renda com aluguel e formar patrimônio; Várias formas de contemplação: sorteio, lances e fidelidades; Acompanhamento da Redecon em cada decisão",
    mapa_titulo: "Um produto, três caminhos",
    mapa_aquisicao: "Comprar, construir ou quitar um financiamento, sem entrada e sem juros.",
    mapa_poupanca: "Guardar com disciplina enquanto o crédito cresce todo ano.",
    mapa_investimento: "Fazer o crédito render, vender a carta ou gerar renda com aluguel.",
    sintese_titulo: "Segurança, liberdade de escolha e rendimento",
    sintese_seg: "Produto regulado e fiscalizado pelo Banco Central; Empresa sólida: Grupo Herval, HS Consórcios e Redecon; Você não se descapitaliza: o seu dinheiro continua aplicado; Constrói patrimônio com disciplina, parcela a parcela",
    sintese_ren: "Rendimento sobre o crédito total, e não sobre o valor pago; O imóvel trabalha a seu favor: o aluguel ajuda a pagar a parcela; Patrimônio em imóvel, que gera renda e pode se valorizar",
    sintese_liq: "Usar o crédito para comprar, construir ou quitar um financiamento; Vender a carta contemplada; Deixar o crédito rendendo até decidir; Várias formas de contemplação: sorteio, lances e fidelidades",
    casos_titulo: "Quem já fez com a Redecon",
    fech_titulo: "O seu plano",
    fech_sub: "Informe a parcela que cabe no seu mês ou o crédito que você quer e veja tudo o que ele pode fazer por você.",
    fech_proximo_t: "Próximo passo",
    fech_proximo: "Escolher o grupo, garantir a sua cota e começar a contar as parcelas em dia para as fidelidades.",
    fim_titulo: "Obrigado pela confiança",
    fim_sub: "Estamos juntos da primeira conversa até a entrega do seu bem.",
    fim_qr: "Acompanhe a Redecon no Instagram",
    aviso_padrao: "Simulação estimada. Valores sujeitos a variações. Não representa promessa de contemplação.",
    aviso_funil: "Concorrência média por modalidade, com base no histórico dos grupos. Não é promessa de contemplação.",
    capa_titulo: "Aquisição, poupança e investimento em um só produto.",
    capa_subtitulo: "Consórcio imobiliário como decisão financeira.",
    regras_titulo: "As regras do jogo",
    regra_investimento_titulo: "Você define o investimento",
    regra_investimento: "Defina quanto quer investir por mês.",
    regra_vencimento_titulo: "Vencimento no dia 10",
    regra_vencimento: "Vencimento todo dia 10. Se cair em fim de semana ou feriado, vai para o próximo dia útil.",
    regra_fidelidade_titulo: "Fidelidade não acumula",
    regra_fidelidade: "As fidelidades exigem parcelas pagas em dia, seguidas. Um dia de atraso zera a contagem e as fidelidades precisam ser conquistadas de novo.",
    funil_titulo: "Quanto mais disciplina, menor a concorrência.",
    otimizar_titulo: "Estratégias para acelerar sua contemplação",
    otimizar_grupo_t: "Escolha do grupo",
    otimizar_grupo: "Prazo e regras de lance mudam de um grupo para outro. Indicamos o grupo que combina com o seu objetivo.",
    otimizar_multicotas_t: "Multicotas",
    otimizar_multicotas: "Dividir o crédito em mais de uma cota coloca mais cotas concorrendo em cada assembleia.",
    otimizar_multicotas_obs: "Faz mais sentido para quem pretende vender a carta. Para usar o crédito todo, é preciso aguardar a contemplação de todas as cotas.",
    otimizar_lance_t: "Lance embutido",
    otimizar_lance: "Até {lance_embutido} do próprio crédito pode ser usado como lance, sem tirar dinheiro do bolso.",
    otimizar_fidelidade_t: "Fidelidade",
    otimizar_fidelidade: "Pagando em dia, você entra em modalidades com bem menos concorrência.",
    aq_usos_titulo: "Um crédito, vários caminhos para o seu imóvel",
    aq_usos_comprar_t: "Comprar",
    aq_usos_comprar: "Casa pronta, apartamento, sala comercial e terreno urbano ou rural.",
    aq_usos_construir_t: "Construir ou reformar",
    aq_usos_construir: "Construção de casa, barracão ou sala comercial, reforma e ampliação.",
    aq_usos_quitar_t: "Quitar financiamento",
    aq_usos_quitar: "Use o crédito para quitar o financiamento e sair dos juros do banco.",
    aq_usos_rodape: "Contemplou e não quer comprar agora? O crédito também pode ser vendido ou ficar rendendo.",
    aq_comp_titulo: "Três formas de comprar o mesmo imóvel",
    po_reaj_titulo: "Cada ano aumenta o seu crédito e reduz o seu custo real",
    po_prev_titulo: "Do crédito para a renda",
    po_prev_sub: "Ao terminar o grupo, o crédito aplicado pode virar renda mensal, por um prazo definido ou para sempre.",
    in_selic_titulo: "Você paga {reajuste_aa} sobre o saldo e recebe rendimento sobre o crédito total",
    in_venda_titulo: "A carta contemplada tem valor de mercado",
    in_aluguel_titulo: "O aluguel pode pagar a parcela",
    po_reaj_sub: "Enquanto a contemplação não vem, o seu dinheiro trabalha: todo ano o crédito é reajustado e o custo real da cota cai. É poupança com disciplina, sem juros, em um sistema regulado pelo Banco Central.",
    po_reaj_sentido: "Enquanto a contemplação não vem, o seu dinheiro não fica parado: o crédito cresce todo ano e o custo real da cota cai.",
    po_prev_sentido: "O consórcio também funciona como previdência: você constrói o valor pagando a parcela e, depois, transforma esse valor em renda.",
    in_selic_sentido: "O saldo devedor diminui a cada parcela, enquanto o crédito aplicado rende sobre o valor total, com a segurança de fundos de grandes bancos.",
    in_venda_sentido: "Quanto mais cedo a contemplação, maior a vantagem da venda sobre uma aplicação comum.",
    in_venda_orientacao_t: "Neste cenário, o CDB rende mais que a venda.",
    in_venda_orientacao: "A orientação da Redecon é outro caminho: usar o crédito para comprar ou construir, deixá-lo rendendo ou formar patrimônio.",
    in_aluguel_sentido: "Com o crédito, você compra ou constrói um imóvel que gera renda. O tipo de imóvel muda muito o resultado.",
    in_barracao_obs: "Construção de custo mais baixo, contratos longos e pouca manutenção, que costuma ficar com a empresa inquilina.",
    compromisso_titulo: "O seu compromisso e o nosso",
    compromisso_cliente_rotulo: "O seu único compromisso",
    compromisso_cliente: "Pagar a parcela em dia.",
    compromisso_redecon_rotulo: "O que a Redecon faz por você",
    compromisso_redecon_itens: "Envia o boleto todo mês; Oferta os lances nas assembleias; Orienta, sugere caminhos e analisa as possibilidades a cada decisão; Acompanha você da primeira conversa até a entrega do bem"
  }
};
